//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarDetail
    {
        public CarDetail()
        {
            this.CarOwner_Rider = new HashSet<CarOwner_Rider>();
        }
    
        public int Id { get; set; }
        public string Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
    
        public virtual ICollection<CarOwner_Rider> CarOwner_Rider { get; set; }
    }
}
