//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarOwner_Rider
    {
        public int Id { get; set; }
        public int CarDetailID { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> RiderID { get; set; }
        public int IsAvailable { get; set; }
        public string Area { get; set; }
    
        public virtual CarDetail CarDetail { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
