//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public Owner()
        {
            this.CarOwner_Rider = new HashSet<CarOwner_Rider>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string OwnerPicture { get; set; }
        public string OwnerInsuranceSlip { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<CarOwner_Rider> CarOwner_Rider { get; set; }
    }
}
