//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rider
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string CCNumber { get; set; }
        public string CCExpiryDate { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public string CCPicture { get; set; }
        public string RiderPicture { get; set; }
    }
}
